import React from 'react'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { Button } from '@/components/ui/button'
import { sessionDetail } from '../medical-agent/[sessionId]/page'
import moment from 'moment'

type props={
    record:sessionDetail
}

type MedicalReport = {
  sessionId: string;
  agent: string;
  user: string;
  timestamp: string;
  chiefComplaint: string;
  summary: string;
  symptoms: string[];
  duration: string;
  severity: string;
  medicationsMentioned: string[];
  recommendations: string[];
};

function ViewReportDialog({record}:props) {

  const parsedReport: MedicalReport | null =
  typeof record?.report === 'string'
    ? JSON.parse(record.report)
    : record?.report ?? null;


  return (
    <Dialog>
  <DialogTrigger>
    <Button variant={'link'} size={'sm'}>View Report</Button>
  </DialogTrigger>
  <DialogContent className="max-h-[90vh] overflow-y-auto ">
    <DialogHeader>
      <DialogTitle asChild>
        <h2 className='text-center text-4xl '>Medical Agent Voice AI Report</h2>
      </DialogTitle>
      <DialogDescription asChild>
        <div className='mt-10'>
            <h2 className='font-bold text-blue-500 text-lg'>Session Info</h2>
            <hr className='bg-blue-500 h-[3px] mb-2'/>
            <div className='grid grid-cols-2'>
                <h2 className='text-black'><span className='font-bold'>Doctor:</span> {record.selectedDoctor?.specialist}</h2>
                <h2 className='text-black'><span className='font-bold'>Consult Date:</span> {moment (new Date(record?.createdOn)).fromNow()}</h2>
                <h2 className='text-black'><span className='font-bold'>User:</span> {parsedReport?.user}</h2>
                <h2 className='text-black'><span className='font-bold'>Agent:</span> {parsedReport?.agent} </h2>
            </div>

            <h2 className='font-bold text-blue-500 text-lg mt-4'>Chief Complaint</h2>
            <hr className='bg-blue-500 h-[3px] mb-2'/>
            <div className='grid'>
                <p className='text-black'>{parsedReport?.chiefComplaint}</p>
            </div>

            <h2 className='font-bold text-blue-500 text-lg mt-4'>Summary</h2>
            <hr className='bg-blue-500 h-[3px] mb-2'/>
            <div className='grid'>
                <p className=' text-black'>{parsedReport?.summary}</p>
            </div>

            <h2 className='font-bold text-blue-500 text-lg mt-4'>Symptoms</h2>
            <hr className='bg-blue-500 h-[3px] mb-2'/>
            <div className='grid'>
                <ul className="list-disc pl-5">
                  {parsedReport?.symptoms?.map((symptom, index) => (
                  <li className=' text-black' key={index}>{symptom}</li>
                  ))}
                </ul>
            </div>

            <h2 className='font-bold text-blue-500 text-lg mt-4'>Duration and Severity</h2>
            <hr className='bg-blue-500 h-[3px] mb-2'/>
            <div className='grid grid-cols-2'>
                <h2 className='text-black'><span className='font-bold'>Duration: </span>{parsedReport?.duration}</h2>
                <h2 className='text-black'><span className='font-bold'>Severity: </span>{parsedReport?.severity}</h2>
            </div>

            <h2 className='font-bold text-blue-500 text-lg mt-4'>Medications Mentioned</h2>
            <hr className='bg-blue-500 h-[3px] mb-2'/>
            <div className='grid grid-cols-2'>
                <ul className="list-disc pl-5">
                  {parsedReport?.medicationsMentioned?.map((medicationsMentioned, index) => (
                  <li className=' text-black' key={index}>{medicationsMentioned}</li>
                  ))}
                </ul>
            </div>

            <h2 className='font-bold text-blue-500 text-lg mt-4'>Recommendations</h2>
            <hr className='bg-blue-500 h-[3px] mb-2'/>
            <div className='grid'>
                <ul className="list-disc pl-5">
                  {parsedReport?.recommendations?.map((recommendations, index) => (
                  <li className=' text-black' key={index}>{recommendations}</li>
                  ))}
                </ul>
            </div>
            
            <hr className='h-[3px] my-4'/>
            <p className='text-center text-xs'>This report is generated by an AI Medical Assistant for informational purposes only</p>
        </div>
      </DialogDescription>
    </DialogHeader>
  </DialogContent>
</Dialog>
  )
}

export default ViewReportDialog